export const authConsts = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

}

export const userConsts = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
}

export const categoryConsts = {
    FETCH_CATEGORIES_REQUEST: "FETCH_CATEGORIES_REQUEST",
    FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
    FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
    ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
}

export const productConsts = {
    FETCH_PRODUCTS_REQUEST: "FETCH_PRODUCTS_REQUEST",
    FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_BY_SLUG_REQUEST: "FETCH_PRODUCTS_BY_SLUG_REQUEST",
    FETCH_PRODUCTS_BY_SLUG_FAILURE: "FETCH_PRODUCTS_BY_SLUG_FAILURE",
    FETCH_PRODUCTS_BY_SLUG_SUCCESS: "FETCH_PRODUCTS_BY_SLUG_SUCCESS",
}