export const authConsts = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

}

export const userConsts = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
}